sources:
  - name: cao
    base: http://crawl.akrasiac.org

    # If the file exists in this path, it will be linked into the data
    # directory from the local path; otherwise it will be fetched
    # using http.
    local: /var/www

    # Timezones are used if this server had games prior to Crawl using
    # only UTC in the logfile.
    timezones:
      D: '-0400'
      S: '-0500'

    utc-epoch: '200808070330+0000'

    # Annotations: standard glob {} expansion is applied. Files
    # flagged * are assumed to be logfiles that are currently being
    # updated and will be refetched, always. Files without * are
    # assumed to be dead versions, and will be fetched only if the
    # local copy is missing.
    logfiles:
      - allgames.txt
      - logfile04
      - logfile05
      - logfile06
      - logfile07{,-sprint}
      - logfile08{,-sprint}
      - logfile09
      - logfile10*
      - logfile11{,-sprint,-zotdef}*
      - logfile-git{,-sprint,-zotdef}*
      - logfile-lorcs: lorcs
    milestones:
      - milestones02
      - milestones03
      - milestones04
      - milestones05
      - milestones06
      - milestones07{,-sprint}
      - milestones08{,-sprint}
      - milestones09
      - milestones10*
      - milestones11{,-sprint,-zotdef}*
      - milestones-git{,-sprint,-zotdef}*
      - milestones-lorcs: lorcs

    # Regex -> location; player name is automatically appended.
    timestamps:
      - http://crawl.akrasiac.org/rawdata

    ttyrecs:
      - https://termcast.shalott.org/ttyrecs/crawl.akrasiac.org/ttyrec
      - http://crawl.akrasiac.org/rawdata

  - name: cdo
    base: http://crawl.develz.org
    utc-epoch: '200808070330+0000'
    timezones:
      D: '+0200'
      S: '+0100'
    logfiles:
      - allgames-0.3.txt
      - allgames-0.4.txt
      - allgames-0.5.txt
      - allgames-0.6.txt
      - allgames{,-spr}-0.7.txt
      - allgames{,-spr,-zd}-0.8.txt*
      - allgames{,-spr,-zd}-0.10.txt*
      - allgames{,-spr,-zd}-0.11.txt*
      - allgames{,-spr,-zd}-0.12.txt*
      - allgames{,-spr,-zd}-svn.txt*
    milestones:
      - milestones-0.3.txt
      - milestones-0.4.txt
      - milestones-0.5.txt
      - milestones-0.6.txt
      - milestones{,-spr}-0.7.txt
      - milestones{,-spr,-zd}-0.8.txt*
      - milestones{,-spr,-zd}-0.10.txt*
      - milestones{,-spr,-zd}-0.11.txt*
      - milestones{,-spr,-zd}-0.12.txt*
      - milestones{,-spr,-zd}-svn.txt*
    timestamps:
      - http://crawl.develz.org/morgues/trunk
      - http://crawl.develz.org/morgues/0.9
      - http://crawl.develz.org/morgues/$file_cv$/$name$
    ttyrecs:
      - https://termcast.shalott.org/ttyrecs/crawl.develz.org/ttyrec
      - ttyrec: http://crawl.develz.org/ttyrecs
        listing: http://crawl.develz.org/cgi-bin/ttyrecs?$name$

  - name: cszo
    base: http://dobrazupa.org
    logfiles:
      - meta/git/logfile{,-sprint,-zotdef}*
      - meta/0.11/logfile{,-sprint,-zotdef}*
      - meta/0.10/logfile{,-sprint,-zotdef}*
    milestones:
      - meta/git/milestones{,-sprint,-zotdef}*
      - meta/0.11/milestones{,-sprint,-zotdef}*
      - meta/0.10/milestones{,-sprint,-zotdef}*
    timestamps:
      - http://dobrazupa.org/morgue
    ttyrecs:
      - https://termcast.shalott.org/ttyrecs/dobrazupa.org/ttyrec
      - http://dobrazupa.org/ttyrec

  - name: csn
    base: http://crawlus.somatika.net
    logfiles:
      - scoring/crawl-trunk/logfile{,-sprint,-zotdef}*
      - scoring/crawl-0.11/logfile{,-sprint,-zotdef}*
    milestones:
      - scoring/crawl-trunk/milestones{,-sprint,-zotdef}*
      - scoring/crawl-0.11/milestones{,-sprint,-zotdef}*
    timestamps:
      - http://crawlus.somatika.net/dumps

  - name: rhf
    base: http://rl.heh.fi/
    logfiles:
      - remote.rhf-logfile-0.5
      - remote.rhf-logfile-0.6
      - remote.rhf-logfile-0.7
      - remote.rhf-logfile-trunk
      - remote.rhf-logfile-spr
    milestones:
      - remote.rhf-milestones-0.5
      - remote.rhf-milestones-0.6
      - remote.rhf-milestones-0.7
      - remote.rhf-milestones-spr
      - remote.rhf-milestones-trunk
    timestamps:
      - http://rl.heh.fi/morgue
    ttyrecs:
      - http://rl.heh.fi/ttyrec


  - name: lbc
    base: http://light.bitprayer.com
    ttyrecs:
      - http://light.bitprayer.com/userdata/$name$/ttyrec
    timestamps:
      - http://light.bitprayer.com/userdata/$name$/morgue

  - name: cue
    base: http://underhound.eu:81/crawl
    timestamps:
      - http://underhound.eu:81/crawl/morgue
    ttyrecs:
      - http://underhound.eu:81/crawl/ttyrec


  - name: ckr
    base: http://kr.dobrazupa.org
    logfiles:
      - www/logfile
    milestones:
      - www/milestones
    morgues:
      - http://kr.dobrazupa.org/morgue/0.13
    ttyrecs:
      - http://kr.dobrazupa.org/ttyrecs
    timestamps:
      - http://kr.dobrazupa.org/morgue/0.13

  - name: cbro
    base: http://crawl.berotato.org/crawl
    timestamps:
      - http://crawl.berotato.org/crawl/morgue
    ttyrecs:
      - https://termcast.shalott.org/ttyrecs/crawl.berotato.org/ttyrec
      - http://crawl.berotato.org/crawl/ttyrec

  - name: cxc
    base: http://crawl.xtahua.com/crawl/meta
    logs:
      - git/{logfile,milestones}{,-sprint,-zotdef}*
    morgues:
      - http://crawl.xtahua.com/crawl/morgue
    timestamps:
      - http://crawl.xtahua.com/crawl/morgue
    ttyrecs:
      - http://crawl.xtahua.com/crawl/ttyrec

  - name: lld
    base: http://lazy-life.ddo.jp/mirror/meta
    logs:
      - '{trunk,0.14}/{logfile,milestones}{,-sprint,-zotdef}*'
      - '0.15/{logfile,milestones}*'
    timestamps:
      - [ 'lld.*-(0.\d+)', 'http://lazy-life.ddo.jp:8080/morgue-$1' ]
      - http://lazy-life.ddo.jp:8080/morgue
    ttyrecs:
      - http://lazy-life.ddo.jp/mirror/ttyrecs

  - name: cpo
    base: https://crawl.project357.org
    logs:
      - dcss-{milestones,logfiles}-{trunk,0.15}*
    timestamps:
      - https://crawl.project357.org/morgue
    ttyrecs:
      - https://crawl.project357.org/ttyrec

  - name: cjr
    base: https://crawl.jorgrun.rocks/meta
    logs:
      - '{0.17,0.18,git}/{milestones,logfile}{,-sprint,-zotdef}*'
    morgues:
      - https://crawl.jorgrun.rocks/morgue
    ttyrecs:
      - https://crawl.jorgrun.rocks/ttyrec

  - name: cko
    base: https://crawl.kelbi.org/crawl/meta
    logs:
      - '{0.21,0.22,git}/{milestones,logfile}{,-sprint,-zotdef}*'
    morgues:
      - https://crawl.kelbi.org/crawl/morgue
    ttyrecs:
      - https://crawl.kelbi.org/crawl/ttyrec

  - name: cwz
    base: https://webzook.net/soup
    logs:
      - '0.16/{logfile,milestones}-old'
      - '{0.13,0.14,0.15,0.16,0.17,0.18,0.19,0.20,0.21,0.22,0.23,0.24,trunk}/{logfile,milestones}*'
    morgues:
      - ['cwz.*/trunk', 'https://webzook.net/soup/morgue/trunk']
      - ['cwz.*/(\d+[.]\d+)', 'https://webzook.net/soup/morgue/$1']
    ttyrecs:
      - https://webzook.net/soup/ttyrecs

  - name: cnc
    base: https://archive.nemelex.cards/meta/
    logs:
      - 'crawl-{0.16,0.17,0.18,0.19,0.20,0.21,0.22,0.23,0.24,0.25,0.26,0.27,0.28,0.29,0.30,0.31,git}/{logfile,milestones}{,-sprint}*'
      - 'crawl-{0.11,0.12,0.13,0.14,0.15}/{logfile,milestones}{,-sprint,-zotdef}*'
    morgues:
      - https://archive.nemelex.cards/morgue
    ttyrecs:
      - https://archive.nemelex.cards/ttyrec
